[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "neuro"
version = "0.1.0"
dependencies = [
    "click",
    "rich",
    "prompt_toolkit",
]

[project.optional-dependencies]
anthropic = ["anthropic"]
openai    = ["openai"]
github    = ["openai"]
all       = ["anthropic", "openai"]

[project.scripts]
neuro = "neuro.cli:main"
